"""ondelete cascade

Revision ID: 09380cdde3ae
Revises: be2fcd85d26a
Create Date: 2024-04-15 18:20:04.578795

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '09380cdde3ae'
down_revision: Union[str, None] = 'be2fcd85d26a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('addresses_user_id_fkey', 'addresses')
    op.create_foreign_key(None, 'addresses', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'addresses', type_='foreignkey')
    op.create_foreign_key('addresses_user_id_fkey', 'addresses', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
