"""roles id is fixed

Revision ID: 6e7d3ce00999
Revises: 47a1c6e2a44b
Create Date: 2024-04-17 22:02:10.351347

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6e7d3ce00999'
down_revision: Union[str, None] = '47a1c6e2a44b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_roles', sa.Column('role_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'user_roles', 'roles', ['role_id'], ['id'], ondelete='CASCADE')
    op.drop_column('user_roles', 'role')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_roles', sa.Column('role', postgresql.ENUM('ADMIN', 'USER', 'SUPER_ADMIN', name='userrole'), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'user_roles', type_='foreignkey')
    op.drop_column('user_roles', 'role_id')
    # ### end Alembic commands ###
