"""remove address id from user model

Revision ID: 979b3843888e
Revises: f03ef6e3fe23
Create Date: 2024-04-13 17:03:01.276758

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '979b3843888e'
down_revision: Union[str, None] = 'f03ef6e3fe23'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('users_address_id_fkey', 'users')
    op.drop_column('users', 'address_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('address_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key('users_address_id_fkey', 'users', 'addresses', ['address_id'], ['id'])
    # ### end Alembic commands ###
