"""roles without enum

Revision ID: f948b766f485
Revises: 6e7d3ce00999
Create Date: 2024-04-18 09:33:13.872181

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f948b766f485'
down_revision: Union[str, None] = '6e7d3ce00999'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('roles', 'name',
               existing_type=postgresql.ENUM('ADMIN', 'USER', 'SUPER_ADMIN', name='userrole'),
               type_=sa.String(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('roles', 'name',
               existing_type=sa.String(),
               type_=postgresql.ENUM('ADMIN', 'USER', 'SUPER_ADMIN', name='userrole'),
               existing_nullable=True)
    # ### end Alembic commands ###
